name: CSV Combination
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    
    steps:
      - uses: actions/checkout@main
      - name: Set up Python all python version
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Test
        run: python -m unittest tests
